---
- hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install system dependencies (Python, build tools, PostgreSQL client, git)
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
          - build-essential
          - libpq-dev
          - postgresql-client
          - git
        state: present

    - name: Create virtualenv for Flask app
      command: python3 -m venv "{{ working_dir }}vagrant_venv"
      args:
        creates: "{{ working_dir }}vagrant_venv"

    - name: Install Python dependencies in virtualenv
      pip:
        requirements: "{{ working_dir }}requirements.txt"
        virtualenv: "{{ working_dir }}vagrant_venv"
        virtualenv_python: python3
