---
- hosts: all
  become: true

  vars:
    common_environment:
      FLASK_APP_NAME: "{{ flask_app_name }}"
      FLASK_ENV: "{{ flask_env }}"
      DOMAIN: "{{ domain }}"
      POSTGRES_HOSTNAME: "{{ postgres_hostname }}"
      POSTGRES_PORT: "{{ postgres_port }}"
      POSTGRES_DATABASE: "{{ postgres_database }}"
      POSTGRES_TEST_DATABASE: "{{ postgres_test_database }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      WORKING_DIR: "{{ working_dir }}"

  tasks:
    - name: Stop any existing Flask application (if running)
      shell: |
        pkill -f "flask run" || true
      args:
        executable: /bin/bash

    - name: Run Flask application in background
      shell: |
        source {{ working_dir }}vagrant_venv/bin/activate
        cd {{ working_dir }}
        nohup flask run --host=0.0.0.0 --port=5000 --reload --debug > app.log 2>&1 &
      args:
        executable: /bin/bash
      environment: "{{ common_environment }}"
      async: 1
      poll: 0
