"""Change temperature, pressure, and uncertainty from Integer to Float in MaterialRecord

Revision ID: c063a020c0c4
Revises: df51c5fdd298
Create Date: 2025-12-11 20:17:34.858760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c063a020c0c4'
down_revision = 'df51c5fdd298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Change temperature, pressure, and uncertainty from Integer to Float in material_record table
    with op.batch_alter_table('material_record', schema=None) as batch_op:
        batch_op.alter_column('temperature',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('pressure',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('uncertainty',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert temperature, pressure, and uncertainty back to Integer
    with op.batch_alter_table('material_record', schema=None) as batch_op:
        batch_op.alter_column('uncertainty',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('pressure',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('temperature',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
